import api from './axios';

const toArr = (d: any): any[] => Array.isArray(d) ? d : (d?.recordset ?? []);
const g = (url: string) => (p?: any) => api.get(url, { params: p }).then((r: any) => toArr(r.data));
const po = (url: string) => (d?: any) => api.post(url, d).then((r: any) => r.data);

export const reportsApi = {
  list: g('/reports'),
  generate: po('/reports/generate'),
  export: po('/reports/export'),
  mail: po('/reports/mail'),
  profitLoss: g('/reports/profit-loss'),
  profitLossFrm: g('/reports/profit-loss-frm'),
  salesAnalysis: g('/reports/sales-analysis'),
  discountSummary: g('/reports/discount-summary'),
  marginReport: g('/reports/margin-report'),
  voucherDetails: g('/reports/voucher-details'),
  journalVoucher: g('/reports/journal-voucher'),
  voucherList: g('/reports/voucher-list'),
  customerBillsDetailed: g('/reports/customer-bills/detailed-summary'),
  customerBillsPending: g('/reports/customer-bills/pending'),
  customerBillsSummary: g('/reports/customer-bills/summary'),
  diagnostic1: g('/reports/diagnostics/custom-1'),
  diagnostic222: g('/reports/diagnostics/custom-2'),
  stockLedger: g('/reports/stock/ledger'),
  customerOutstanding: g('/customers/outstanding/salesmanwise'),
  supplierOutstanding: g('/suppliers/outstanding-summary'),
  acSummary: g('/accounts/summary'),
  groupBalance: g('/accounts/group-balance'),
  balanceSheet: g('/accounts/summary-balance-sheet'),
  agewiseDetails: g('/accounts/agewise-details'),
  salesCategorySummary: g('/sales/category-summary'),
  salesLabourParts: g('/sales/labour-parts-report'),
  monthlySales: g('/sales/monthly-summary'),
  salesmanInvoices: g('/sales/invoices/summary-by-staff'),
  stockValuation: g('/stock/valuation'),
  stockAging: g('/stock/aging'),
  openingStock: g('/stock/opening-balances'),
  usedCars: g('/inventory/used-cars'),
  workInProgress: g('/jobs/work-in-progress-report'),
  technicianEfficiency: g('/technicians/efficiency'),
  employeeAttendance: g('/employee-attendance'),
  vehicleAttendance: g('/vehicle-attendance'),
  salaryRegister: g('/payroll/salary-register'),
  salarySlip: (empId: string, period: string) => api.get(`/payroll/salary-slip/${empId}/${period}`).then((r: any) => r.data),
  omasters: g('/admin/omasters-report'),
  companyHeader: g('/company/report-header'),
  updateCompanyHeader: (d: any) => api.patch('/company/report-header', d).then((r: any) => r.data),
};
